/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.concesionariongg.Modelos;

import com.mongodb.client.FindIterable;
import com.mycompany.concesionariongg.Conexion.Conexion;
import com.mycompany.Trabajador.MenuPrincipalComercial;
import java.awt.Color;
import static java.awt.Component.CENTER_ALIGNMENT;
import java.awt.Font;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;

/**
 *
 * @author nesto
 */
public class Modelos extends javax.swing.JFrame {

    Conexion conexion = new Conexion();
    private int seleccionFila;

    /**
     * Creates new form InicioStock
     */
    public Modelos() {
        initComponents();
        //Se establece el titulo de la ventana
        setTitle("CONCESIONARIO NGG");
        //Se cambia el color de fondo de la ventana
        getContentPane().setBackground(new Color(128, 0, 128));
        //Se crea el borde del jpanel
        Border borde = BorderFactory.createLineBorder(Color.white, 5);
        //Se añade el titulo
        jLabelTexto.setFont(new Font("Arial", Font.BOLD, 24));
        jLabelTexto.setForeground(Color.WHITE);
        jLabelTexto.setAlignmentX(CENTER_ALIGNMENT);
        //Se añade el logo
        String ruta = "C:/Users/nesto/Documents/NetBeansProjects/ConcesionarioNGG/imagenes/logo.png";
        Image foto = new ImageIcon(ruta).getImage();
        Image nuevaImagen = foto.getScaledInstance(130, 130, Image.SCALE_SMOOTH);
        ImageIcon imagen = new ImageIcon(nuevaImagen);
        jLabelLogo.setIcon(imagen);
        pack();
        //Se decoran los distintos jpanel
        jPanelFiltros.setBorder(borde);
        jPanelFiltros.setBackground(new Color(128, 0, 128));

        jPanelKm.setBorder(borde);
        jPanelKm.setBackground(new Color(128, 0, 128));

        jPanelPrecio.setBorder(borde);
        jPanelPrecio.setBackground(new Color(128, 0, 128));
        //Se decoran los jlabel
        jLabelMarca.setFont(new Font("Arial", Font.BOLD, 12));
        jLabelMarca.setForeground(Color.WHITE);

        jLabelModelo.setFont(new Font("Arial", Font.BOLD, 12));
        jLabelModelo.setForeground(Color.WHITE);

        jLabelMotor.setFont(new Font("Arial", Font.BOLD, 12));
        jLabelMotor.setForeground(Color.WHITE);

        jLabelCombustible.setFont(new Font("Arial", Font.BOLD, 12));
        jLabelCombustible.setForeground(Color.WHITE);

        jLabelKmsMin.setFont(new Font("Arial", Font.BOLD, 12));
        jLabelKmsMin.setForeground(Color.WHITE);

        jLabelKmMax.setFont(new Font("Arial", Font.BOLD, 12));
        jLabelKmMax.setForeground(Color.WHITE);

        jLabelAño.setFont(new Font("Arial", Font.BOLD, 12));
        jLabelAño.setForeground(Color.WHITE);

        jLabelPrecioMin.setFont(new Font("Arial", Font.BOLD, 12));
        jLabelPrecioMin.setForeground(Color.WHITE);

        jLabelPrecioMax.setFont(new Font("Arial", Font.BOLD, 12));
        jLabelPrecioMax.setForeground(Color.WHITE);

        jLabelCambio.setFont(new Font("Arial", Font.BOLD, 12));
        jLabelCambio.setForeground(Color.WHITE);

        jLabelEstado.setFont(new Font("Arial", Font.BOLD, 12));
        jLabelEstado.setForeground(Color.WHITE);
        //Se decoran los botones
        jButtonVolver.setFont(new Font("Arial", Font.BOLD, 12));
        jButtonVolver.setBackground(Color.WHITE);

        jButtonFiltrar.setFont(new Font("Arial", Font.BOLD, 12));
        jButtonFiltrar.setBackground(Color.WHITE);

        jButtonSiguiente.setFont(new Font("Arial", Font.BOLD, 12));
        jButtonSiguiente.setBackground(Color.WHITE);
        //Se coloca la ventana en el centro de la pantalla
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox9 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jButtonFiltrar = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableModelos = new javax.swing.JTable();
        jButtonSiguiente = new javax.swing.JButton();
        jPanelFiltros = new javax.swing.JPanel();
        jTextFieldMarca = new javax.swing.JTextField();
        jLabelMarca = new javax.swing.JLabel();
        jTextFieldAnyo = new javax.swing.JTextField();
        jLabelAño = new javax.swing.JLabel();
        jTextFieldCambio = new javax.swing.JTextField();
        jLabelCambio = new javax.swing.JLabel();
        jTextFieldModelo = new javax.swing.JTextField();
        jLabelModelo = new javax.swing.JLabel();
        jTextFieldCombustible = new javax.swing.JTextField();
        jLabelCombustible = new javax.swing.JLabel();
        jTextFieldMotor = new javax.swing.JTextField();
        jLabelMotor = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jTextFieldEstado = new javax.swing.JTextField();
        jPanelPrecio = new javax.swing.JPanel();
        jTextFieldPrecioMin = new javax.swing.JTextField();
        jLabelPrecioMin = new javax.swing.JLabel();
        jTextFieldPrecioMax = new javax.swing.JTextField();
        jLabelPrecioMax = new javax.swing.JLabel();
        jPanelKm = new javax.swing.JPanel();
        jTextFieldKmMin = new javax.swing.JTextField();
        jLabelKmsMin = new javax.swing.JLabel();
        jTextFieldKmMax = new javax.swing.JTextField();
        jLabelKmMax = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelTexto = new javax.swing.JLabel();

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(850, 780));

        jButtonFiltrar.setText("Filtrar");
        jButtonFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiltrarActionPerformed(evt);
            }
        });

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jTableModelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableModelos);

        jButtonSiguiente.setText("Siguiente");
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });

        jLabelMarca.setText("Marca");

        jLabelAño.setText("Año");

        jLabelCambio.setText("Cambio");

        jLabelModelo.setText("Modelo");

        jLabelCombustible.setText("Combustible");

        jLabelMotor.setText("Motor");

        jLabelEstado.setText("Estado(Segundamano,Km0,Nuevo)");

        jTextFieldEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFiltrosLayout = new javax.swing.GroupLayout(jPanelFiltros);
        jPanelFiltros.setLayout(jPanelFiltrosLayout);
        jPanelFiltrosLayout.setHorizontalGroup(
            jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFiltrosLayout.createSequentialGroup()
                        .addGroup(jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAño)
                            .addGroup(jPanelFiltrosLayout.createSequentialGroup()
                                .addComponent(jTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelModelo)
                                    .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCombustible)
                            .addComponent(jTextFieldMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelFiltrosLayout.createSequentialGroup()
                        .addGroup(jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMarca)
                            .addGroup(jPanelFiltrosLayout.createSequentialGroup()
                                .addComponent(jTextFieldAnyo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCambio)
                                    .addComponent(jTextFieldCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFiltrosLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabelMotor))
                            .addGroup(jPanelFiltrosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelFiltrosLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabelEstado)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanelFiltrosLayout.setVerticalGroup(
            jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltrosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMarca)
                    .addComponent(jLabelModelo)
                    .addComponent(jLabelMotor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAño)
                    .addComponent(jLabelCambio)
                    .addComponent(jLabelCombustible))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAnyo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEstado))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jLabelPrecioMin.setText("Precio Min");

        jTextFieldPrecioMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioMaxActionPerformed(evt);
            }
        });

        jLabelPrecioMax.setText("Precio Max");

        javax.swing.GroupLayout jPanelPrecioLayout = new javax.swing.GroupLayout(jPanelPrecio);
        jPanelPrecio.setLayout(jPanelPrecioLayout);
        jPanelPrecioLayout.setHorizontalGroup(
            jPanelPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrecioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldPrecioMax, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldPrecioMin, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPrecioMin)
                        .addComponent(jLabelPrecioMax)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanelPrecioLayout.setVerticalGroup(
            jPanelPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrecioLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelPrecioMin)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldPrecioMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelPrecioMax)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldPrecioMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jLabelKmsMin.setText("Kms Min");

        jLabelKmMax.setText("Kms Max");

        javax.swing.GroupLayout jPanelKmLayout = new javax.swing.GroupLayout(jPanelKm);
        jPanelKm.setLayout(jPanelKmLayout);
        jPanelKmLayout.setHorizontalGroup(
            jPanelKmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKmLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelKmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelKmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldKmMin, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                        .addComponent(jLabelKmsMin)
                        .addComponent(jTextFieldKmMax))
                    .addComponent(jLabelKmMax))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanelKmLayout.setVerticalGroup(
            jPanelKmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKmLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelKmsMin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldKmMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jLabelKmMax)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldKmMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jLabelTexto.setText("FILTRADO DE MODELOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonVolver)
                        .addGap(270, 270, 270)
                        .addComponent(jButtonFiltrar)
                        .addGap(255, 255, 255)
                        .addComponent(jButtonSiguiente))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jPanelFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jPanelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addComponent(jLabelTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanelKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTexto)
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVolver)
                    .addComponent(jButtonFiltrar)
                    .addComponent(jButtonSiguiente))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiltrarActionPerformed

        //Se modifican los datos de los jtextfield para que tengan la primera letra en mayuscula y de igual como lo ponga el trabajador y se guardan
        String marca = jTextFieldMarca.getText().toLowerCase();
        String marcaFormateado;
        if (!marca.isEmpty()) {
            marcaFormateado = marca.substring(0, 1).toUpperCase() + marca.substring(1);
        } else {
            marcaFormateado = "";
        }
        String modelo = (String) jTextFieldModelo.getText().toLowerCase();
        String modeloFormateado;
        if (!modelo.isEmpty()) {
            modeloFormateado = modelo.substring(0, 1).toUpperCase() + modelo.substring(1);
        } else {
            modeloFormateado = "";
        }
        String motor = (String) jTextFieldMotor.getText().toLowerCase();
        String motorFormateado;
        if (!motor.isEmpty()) {
            motorFormateado = motor.substring(0, 1).toUpperCase() + motor.substring(1);
        } else {
            motorFormateado = "";
        }
        String combustible = (String) jTextFieldCombustible.getText().toLowerCase();
        String combustibleFormateado;
        if (!combustible.isEmpty()) {
            combustibleFormateado = combustible.substring(0, 1).toUpperCase() + combustible.substring(1);
        } else {
            combustibleFormateado = "";
        }
        int kmMin;
        String kmMinString = jTextFieldKmMin.getText();
        if (!kmMinString.isEmpty()) {
            kmMin = Integer.parseInt(kmMinString);
        } else {
            kmMin = 0;
        }

        int kmMax;
        String kmMaxString = jTextFieldKmMax.getText();
        if (!kmMaxString.isEmpty()) {
            kmMax = Integer.parseInt(kmMaxString);
        } else {
            kmMax = Integer.MAX_VALUE;
        }

        String anyo = jTextFieldAnyo.getText();

        int precioMin;
        String precioMinString = jTextFieldPrecioMin.getText();
        if (!precioMinString.isEmpty()) {
            precioMin = Integer.parseInt(precioMinString);
        } else {
            precioMin = 0;
        }

        int precioMax;
        String precioMaxString = jTextFieldPrecioMax.getText();
        if (!precioMaxString.isEmpty()) {
            precioMax = Integer.parseInt(precioMaxString);
        } else {
            precioMax = Integer.MAX_VALUE;
        }

        String cambio = (String) jTextFieldCambio.getText().toLowerCase();
        String cambioFormateado;
        if (!cambio.isEmpty()) {
            cambioFormateado = cambio.substring(0, 1).toUpperCase() + cambio.substring(1);
        } else {
            cambioFormateado = "";
        }
        String estado = (String) jTextFieldEstado.getText().toLowerCase();
        String estadoFormateado;
        if (!estado.isEmpty()) {
            estadoFormateado = estado.substring(0, 1).toUpperCase() + estado.substring(1);
        } else {
            estadoFormateado = "";
        }
        List<Document> filtro = encontrarDatosConElFiltro(marcaFormateado, modeloFormateado, motorFormateado, combustibleFormateado, kmMin, kmMax, precioMin, precioMax, anyo, cambioFormateado, estadoFormateado);
        crearTabla(filtro);

    }//GEN-LAST:event_jButtonFiltrarActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        MenuPrincipalComercial newframe = new MenuPrincipalComercial();

        newframe.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        // TODO add your handling code here:
        pasarDatosFiladeVentana();

        DatosModelo newframe = new DatosModelo();

        newframe.setVisible(true);

        this.dispose();

    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void jTextFieldPrecioMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioMaxActionPerformed

    private void jTextFieldEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEstadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        // Iniciar el hilo
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modelos().setVisible(true);
            }
        });
    }

    private void pasarDatosFiladeVentana() {
        //Se guardan los datos de la fila seleccionada de la tabla y se pasan de ventana
        seleccionFila = jTableModelos.getSelectedRow();
        String marca = String.valueOf(jTableModelos.getValueAt(seleccionFila, 0));
        String modelo = String.valueOf(jTableModelos.getValueAt(seleccionFila, 1));
        String motor = String.valueOf(jTableModelos.getValueAt(seleccionFila, 2));
        String combustible = String.valueOf(jTableModelos.getValueAt(seleccionFila, 3));
        String km = String.valueOf(jTableModelos.getValueAt(seleccionFila, 4));
        String precio = String.valueOf(jTableModelos.getValueAt(seleccionFila, 5));
        String anyo = String.valueOf(jTableModelos.getValueAt(seleccionFila, 6));
        String cambio = String.valueOf(jTableModelos.getValueAt(seleccionFila, 7));
        String estado = String.valueOf(jTableModelos.getValueAt(seleccionFila, 8));

        DatosModelo.marca = marca;
        DatosModelo.modelo = modelo;
        DatosModelo.motor = motor;
        DatosModelo.combustible = combustible;
        DatosModelo.km = km;
        DatosModelo.anyo = anyo;
        DatosModelo.precio = precio;
        DatosModelo.cambio = cambio;
        DatosModelo.estado = estado;
    }

    private List<Document> encontrarDatosConElFiltro(String marcaFormateado, String modeloFormateado, String motorFormateado, String combustibleFormateado, int kmMin, int kmMax, int precioMin, int precioMax, String anyo, String cambioFormateado, String estadoFormateado) {
        //Se crea el filtro para sacar los datos en la tabla
        List<Document> consulta = new ArrayList<>();
        Document filtros = new Document();
        if (!marcaFormateado.isEmpty()) {
            filtros.append("Marca", marcaFormateado);
        }
        if (!modeloFormateado.isEmpty()) {
            filtros.append("Modelo", modeloFormateado);
        }
        if (!motorFormateado.isEmpty()) {
            filtros.append("Motor", motorFormateado);
        }
        if (!combustibleFormateado.isEmpty()) {
            filtros.append("Combustible", combustibleFormateado);
        }
        if (kmMin != 0 || kmMax != 0 || (kmMin == 0 && kmMax == 0)) {
            Document kmFiltro = new Document();
            if (kmMin != 0) {
                kmFiltro.append("$gte", kmMin);
            }
            if (kmMax != 0) {
                kmFiltro.append("$lt", kmMax);
            }
            filtros.append("Km", kmFiltro);
        }
        if (precioMin != 0 || precioMax != 0) {
            Document precioFiltro = new Document();
            if (precioMin != 0) {
                precioFiltro.append("$gte", precioMin);
            }
            if (precioMax != 0) {
                precioFiltro.append("$lt", precioMax);
            }
            filtros.append("Precio", precioFiltro);
        }
        if (!anyo.isEmpty()) {
            filtros.append("Anyo", anyo);
        }
        if (!cambioFormateado.isEmpty()) {
            filtros.append("Cambio", cambioFormateado);
        }
        if (!estadoFormateado.isEmpty()) {
            filtros.append("Estado", estadoFormateado);
        }

        FindIterable<Document> d = conexion.col_Modelos.find(filtros);
        for (Document doc : d) {
            consulta.add(doc);
        }

        return consulta;
    }

    private void crearTabla(List<Document> filtro) {
        //Se le dal el formato a la tabal y se añaden las columnas y las filas
        DefaultTableModel tabla = new DefaultTableModel();
        String[] columnas = {"Marca", "Modelo", "Motor", "Combustible", "Km", "Precio", "Anyo", "Cambio", "Estado"};
        tabla.setColumnIdentifiers(columnas);
        jTableModelos.setModel(tabla);
        jTableModelos.setRowSelectionAllowed(true);
        for (Document d : filtro) {
            Object[] filas = {d.get("Marca"), d.get("Modelo"), d.get("Motor"), d.get("Combustible"), d.get("Km"), d.get("Precio"), d.get("Anyo"), d.get("Cambio"), d.get("Estado")};
            tabla.addRow(filas);
        }

        jTableModelos.setFont(new Font("Arial", Font.BOLD, 12));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFiltrar;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabelAño;
    private javax.swing.JLabel jLabelCambio;
    private javax.swing.JLabel jLabelCombustible;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelKmMax;
    private javax.swing.JLabel jLabelKmsMin;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelMotor;
    private javax.swing.JLabel jLabelPrecioMax;
    private javax.swing.JLabel jLabelPrecioMin;
    private javax.swing.JLabel jLabelTexto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelFiltros;
    private javax.swing.JPanel jPanelKm;
    private javax.swing.JPanel jPanelPrecio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableModelos;
    private javax.swing.JTextField jTextFieldAnyo;
    private javax.swing.JTextField jTextFieldCambio;
    private javax.swing.JTextField jTextFieldCombustible;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JTextField jTextFieldKmMax;
    private javax.swing.JTextField jTextFieldKmMin;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldModelo;
    private javax.swing.JTextField jTextFieldMotor;
    private javax.swing.JTextField jTextFieldPrecioMax;
    private javax.swing.JTextField jTextFieldPrecioMin;
    // End of variables declaration//GEN-END:variables
}
